/**
 * ISO helpers for Search Console country codes (alpha-3) ↔ world-atlas numeric IDs.
 * GSC returns lowercase alpha-3 (e.g. "usa", "gbr", "pak").
 */

/** ISO 3166-1 numeric → alpha-3 */
export const NUMERIC_TO_ALPHA3 = {
  4: "afg",
  8: "alb",
  12: "dza",
  20: "and",
  24: "ago",
  28: "atg",
  31: "aze",
  32: "arg",
  36: "aus",
  40: "aut",
  44: "bhs",
  48: "bhr",
  50: "bgd",
  51: "arm",
  52: "brb",
  56: "bel",
  64: "btn",
  68: "bol",
  70: "bih",
  72: "bwa",
  76: "bra",
  84: "blz",
  90: "slb",
  96: "brn",
  100: "bgr",
  104: "mmr",
  108: "bdi",
  112: "blr",
  116: "khm",
  120: "cmr",
  124: "can",
  132: "cpv",
  140: "caf",
  144: "lka",
  148: "tcd",
  152: "chl",
  156: "chn",
  158: "twn",
  170: "col",
  174: "com",
  178: "cog",
  180: "cod",
  188: "cri",
  191: "hrv",
  192: "cub",
  196: "cyp",
  203: "cze",
  204: "ben",
  208: "dnk",
  212: "dma",
  214: "dom",
  218: "ecu",
  222: "slv",
  226: "gnq",
  231: "eth",
  232: "eri",
  233: "est",
  242: "fji",
  246: "fin",
  250: "fra",
  262: "dji",
  266: "gab",
  268: "geo",
  270: "gmb",
  275: "pse",
  276: "deu",
  288: "gha",
  300: "grc",
  304: "grl",
  320: "gtm",
  324: "gin",
  328: "guy",
  332: "hti",
  340: "hnd",
  348: "hun",
  352: "isl",
  356: "ind",
  360: "idn",
  364: "irn",
  368: "irq",
  372: "irl",
  376: "isr",
  380: "ita",
  388: "jam",
  392: "jpn",
  398: "kaz",
  400: "jor",
  404: "ken",
  408: "prk",
  410: "kor",
  414: "kwt",
  417: "kgz",
  418: "lao",
  422: "lbn",
  426: "lso",
  428: "lva",
  430: "lbr",
  434: "lby",
  438: "lie",
  440: "ltu",
  442: "lux",
  450: "mdg",
  454: "mwi",
  458: "mys",
  462: "mdv",
  466: "mli",
  470: "mlt",
  478: "mrt",
  480: "mus",
  484: "mex",
  492: "mco",
  496: "mng",
  498: "mda",
  499: "mne",
  504: "mar",
  508: "moz",
  512: "omn",
  516: "nam",
  524: "npl",
  528: "nld",
  554: "nzl",
  558: "nic",
  562: "ner",
  566: "nga",
  578: "nor",
  586: "pak",
  591: "pan",
  598: "png",
  600: "pry",
  604: "per",
  608: "phl",
  616: "pol",
  620: "prt",
  624: "gnb",
  626: "tls",
  634: "qat",
  642: "rou",
  643: "rus",
  646: "rwa",
  682: "sau",
  686: "sen",
  688: "srb",
  690: "syc",
  694: "sle",
  702: "sgp",
  703: "svk",
  704: "vnm",
  705: "svn",
  706: "som",
  710: "zaf",
  716: "zwe",
  724: "esp",
  728: "ssd",
  729: "sdn",
  732: "esh",
  740: "sur",
  748: "swz",
  752: "swe",
  756: "che",
  760: "syr",
  762: "tjk",
  764: "tha",
  768: "tgo",
  780: "tto",
  784: "are",
  788: "tun",
  792: "tur",
  795: "tkm",
  800: "uga",
  804: "ukr",
  807: "mkd",
  818: "egy",
  826: "gbr",
  834: "tza",
  840: "usa",
  854: "bfa",
  858: "ury",
  860: "uzb",
  862: "ven",
  887: "yem",
  894: "zmb",
};

export const COUNTRY_DISPLAY_NAMES = {
  afg: "Afghanistan",
  alb: "Albania",
  dza: "Algeria",
  and: "Andorra",
  ago: "Angola",
  atg: "Antigua and Barbuda",
  arg: "Argentina",
  arm: "Armenia",
  aus: "Australia",
  aut: "Austria",
  aze: "Azerbaijan",
  bhs: "Bahamas",
  bhr: "Bahrain",
  bgd: "Bangladesh",
  brb: "Barbados",
  blr: "Belarus",
  bel: "Belgium",
  blz: "Belize",
  ben: "Benin",
  btn: "Bhutan",
  bol: "Bolivia",
  bih: "Bosnia and Herzegovina",
  bwa: "Botswana",
  bra: "Brazil",
  brn: "Brunei",
  bgr: "Bulgaria",
  bfa: "Burkina Faso",
  bdi: "Burundi",
  khm: "Cambodia",
  cmr: "Cameroon",
  can: "Canada",
  cpv: "Cape Verde",
  caf: "Central African Republic",
  tcd: "Chad",
  chl: "Chile",
  chn: "China",
  col: "Colombia",
  com: "Comoros",
  cog: "Congo",
  cod: "DR Congo",
  cri: "Costa Rica",
  hrv: "Croatia",
  cub: "Cuba",
  cyp: "Cyprus",
  cze: "Czechia",
  dnk: "Denmark",
  dji: "Djibouti",
  dma: "Dominica",
  dom: "Dominican Republic",
  ecu: "Ecuador",
  egy: "Egypt",
  slv: "El Salvador",
  gnq: "Equatorial Guinea",
  eri: "Eritrea",
  est: "Estonia",
  eth: "Ethiopia",
  fji: "Fiji",
  fin: "Finland",
  fra: "France",
  gab: "Gabon",
  gmb: "Gambia",
  geo: "Georgia",
  deu: "Germany",
  gha: "Ghana",
  grc: "Greece",
  gtm: "Guatemala",
  gin: "Guinea",
  gnb: "Guinea-Bissau",
  guy: "Guyana",
  hti: "Haiti",
  hnd: "Honduras",
  hun: "Hungary",
  isl: "Iceland",
  ind: "India",
  idn: "Indonesia",
  irn: "Iran",
  irq: "Iraq",
  irl: "Ireland",
  isr: "Israel",
  ita: "Italy",
  jam: "Jamaica",
  jpn: "Japan",
  jor: "Jordan",
  kaz: "Kazakhstan",
  ken: "Kenya",
  prk: "North Korea",
  kor: "South Korea",
  kwt: "Kuwait",
  kgz: "Kyrgyzstan",
  lao: "Laos",
  lva: "Latvia",
  lbn: "Lebanon",
  lso: "Lesotho",
  lbr: "Liberia",
  lby: "Libya",
  lie: "Liechtenstein",
  ltu: "Lithuania",
  lux: "Luxembourg",
  mdg: "Madagascar",
  mwi: "Malawi",
  mys: "Malaysia",
  mdv: "Maldives",
  mli: "Mali",
  mlt: "Malta",
  mrt: "Mauritania",
  mus: "Mauritius",
  mex: "Mexico",
  mda: "Moldova",
  mco: "Monaco",
  mng: "Mongolia",
  mne: "Montenegro",
  mar: "Morocco",
  moz: "Mozambique",
  mmr: "Myanmar",
  nam: "Namibia",
  npl: "Nepal",
  nld: "Netherlands",
  nzl: "New Zealand",
  nic: "Nicaragua",
  ner: "Niger",
  nga: "Nigeria",
  mkd: "North Macedonia",
  nor: "Norway",
  omn: "Oman",
  pak: "Pakistan",
  pan: "Panama",
  png: "Papua New Guinea",
  pry: "Paraguay",
  per: "Peru",
  phl: "Philippines",
  pol: "Poland",
  prt: "Portugal",
  qat: "Qatar",
  rou: "Romania",
  rus: "Russia",
  rwa: "Rwanda",
  sau: "Saudi Arabia",
  sen: "Senegal",
  srb: "Serbia",
  syc: "Seychelles",
  sle: "Sierra Leone",
  sgp: "Singapore",
  svk: "Slovakia",
  svn: "Slovenia",
  slb: "Solomon Islands",
  som: "Somalia",
  zaf: "South Africa",
  ssd: "South Sudan",
  esp: "Spain",
  lka: "Sri Lanka",
  sdn: "Sudan",
  sur: "Suriname",
  swz: "Eswatini",
  swe: "Sweden",
  che: "Switzerland",
  syr: "Syria",
  twn: "Taiwan",
  tjk: "Tajikistan",
  tza: "Tanzania",
  tha: "Thailand",
  tls: "Timor-Leste",
  tgo: "Togo",
  tto: "Trinidad and Tobago",
  tun: "Tunisia",
  tur: "Turkey",
  tkm: "Turkmenistan",
  uga: "Uganda",
  ukr: "Ukraine",
  are: "United Arab Emirates",
  gbr: "United Kingdom",
  usa: "United States",
  ury: "Uruguay",
  uzb: "Uzbekistan",
  ven: "Venezuela",
  vnm: "Vietnam",
  yem: "Yemen",
  zmb: "Zambia",
  zwe: "Zimbabwe",
  pse: "Palestine",
  grl: "Greenland",
  esh: "Western Sahara",
  us: "United States",
  pk: "Pakistan",
  ca: "Canada",
  cn: "China",
  de: "Germany",
  fr: "France",
  ie: "Ireland",
  gb: "United Kingdom",
  in: "India",
};

const ALPHA2_TO_ALPHA3 = {
  ad: "and",
  ae: "are",
  af: "afg",
  al: "alb",
  am: "arm",
  ao: "ago",
  ar: "arg",
  at: "aut",
  au: "aus",
  az: "aze",
  ba: "bih",
  bd: "bgd",
  be: "bel",
  bf: "bfa",
  bg: "bgr",
  bh: "bhr",
  bi: "bdi",
  bj: "ben",
  bn: "brn",
  bo: "bol",
  br: "bra",
  bs: "bhs",
  bt: "btn",
  bw: "bwa",
  by: "blr",
  bz: "blz",
  ca: "can",
  cd: "cod",
  cf: "caf",
  cg: "cog",
  ch: "che",
  cl: "chl",
  cm: "cmr",
  cn: "chn",
  co: "col",
  cr: "cri",
  cu: "cub",
  cv: "cpv",
  cy: "cyp",
  cz: "cze",
  de: "deu",
  dj: "dji",
  dk: "dnk",
  dm: "dma",
  do: "dom",
  dz: "dza",
  ec: "ecu",
  ee: "est",
  eg: "egy",
  er: "eri",
  es: "esp",
  et: "eth",
  fi: "fin",
  fj: "fji",
  fr: "fra",
  ga: "gab",
  gb: "gbr",
  ge: "geo",
  gh: "gha",
  gm: "gmb",
  gn: "gin",
  gq: "gnq",
  gr: "grc",
  gt: "gtm",
  gy: "guy",
  hn: "hnd",
  hr: "hrv",
  ht: "hti",
  hu: "hun",
  id: "idn",
  ie: "irl",
  il: "isr",
  in: "ind",
  iq: "irq",
  ir: "irn",
  is: "isl",
  it: "ita",
  jm: "jam",
  jo: "jor",
  jp: "jpn",
  ke: "ken",
  kg: "kgz",
  kh: "khm",
  kr: "kor",
  kw: "kwt",
  kz: "kaz",
  lb: "lbn",
  lk: "lka",
  lr: "lbr",
  lt: "ltu",
  lu: "lux",
  lv: "lva",
  ly: "lby",
  ma: "mar",
  mc: "mco",
  md: "mda",
  me: "mne",
  mg: "mdg",
  mk: "mkd",
  ml: "mli",
  mm: "mmr",
  mn: "mng",
  mr: "mrt",
  mt: "mlt",
  mu: "mus",
  mv: "mdv",
  mw: "mwi",
  mx: "mex",
  my: "mys",
  mz: "moz",
  na: "nam",
  ne: "ner",
  ng: "nga",
  ni: "nic",
  nl: "nld",
  no: "nor",
  np: "npl",
  nz: "nzl",
  om: "omn",
  pa: "pan",
  pe: "per",
  pg: "png",
  ph: "phl",
  pk: "pak",
  pl: "pol",
  ps: "pse",
  pt: "prt",
  py: "pry",
  qa: "qat",
  ro: "rou",
  rs: "srb",
  ru: "rus",
  rw: "rwa",
  sa: "sau",
  sb: "slb",
  sc: "syc",
  sd: "sdn",
  se: "swe",
  sg: "sgp",
  si: "svn",
  sk: "svk",
  sl: "sle",
  sn: "sen",
  so: "som",
  sr: "sur",
  ss: "ssd",
  sv: "slv",
  sy: "syr",
  sz: "swz",
  td: "tcd",
  tg: "tgo",
  th: "tha",
  tj: "tjk",
  tl: "tls",
  tm: "tkm",
  tn: "tun",
  tr: "tur",
  tt: "tto",
  tw: "twn",
  tz: "tza",
  ua: "ukr",
  ug: "uga",
  us: "usa",
  uy: "ury",
  uz: "uzb",
  ve: "ven",
  vn: "vnm",
  ye: "yem",
  za: "zaf",
  zm: "zmb",
  zw: "zwe",
};

const INPUT_ALIASES = {
  uk: "gb",
  britain: "gb",
  "great britain": "gb",
  england: "gb",
  usa: "us",
  america: "us",
  "united states of america": "us",
  uae: "ae",
  korea: "kr",
  "south korea": "kr",
};

function iso2FromAlpha3(alpha3) {
  const a3 = String(alpha3 || "").toLowerCase();
  if (!a3) return "";
  for (const [a2, mapped] of Object.entries(ALPHA2_TO_ALPHA3)) {
    if (mapped === a3) return a2;
  }
  return "";
}

/** ISO 3166-1 alpha-2 from a name, code, or alias. Empty if unknown. */
export function iso2FromCountryInput(raw) {
  const q = String(raw || "")
    .trim()
    .toLowerCase()
    .replace(/\./g, " ")
    .replace(/\s+/g, " ")
    .trim();
  if (!q) return "";
  if (INPUT_ALIASES[q]) return INPUT_ALIASES[q];
  if (/^[a-z]{2}$/.test(q)) return q === "uk" ? "gb" : q;
  if (/^[a-z]{3}$/.test(q)) return iso2FromAlpha3(q) || "";
  let found2 = "";
  let found3 = "";
  for (const [code, name] of Object.entries(COUNTRY_DISPLAY_NAMES)) {
    if (String(name).toLowerCase() !== q) continue;
    if (code.length === 2) found2 = code === "uk" ? "gb" : code;
    else if (code.length === 3 && !found3) found3 = code;
  }
  if (found2) return found2;
  if (found3) return iso2FromAlpha3(found3);
  return "";
}

export function sameCountryCode(a, b) {
  const left = iso2FromCountryInput(a) || normalizeCountryCode(a);
  const right = iso2FromCountryInput(b) || normalizeCountryCode(b);
  if (!left || !right) return false;
  if (left === right) return true;
  return normalizeCountryCode(left) === normalizeCountryCode(right);
}

export function normalizeCountryCode(raw) {
  const code = String(raw || "").trim().toLowerCase();
  if (!code || code === "unknown" || code === "zzz") return "";
  if (code.length === 3) return code;
  if (code.length === 2) return ALPHA2_TO_ALPHA3[code] || code;
  return code;
}

export function countryDisplayName(raw) {
  const code = normalizeCountryCode(raw);
  if (!code) return "Unknown";
  return (
    COUNTRY_DISPLAY_NAMES[code] ||
    COUNTRY_DISPLAY_NAMES[String(raw || "").toLowerCase()] ||
    code.toUpperCase()
  );
}

export function alpha3FromNumericId(numericId) {
  const n = Number(numericId);
  if (!Number.isFinite(n)) return "";
  return NUMERIC_TO_ALPHA3[n] || "";
}
