function item(label, body) {
  return { label, body };
}

function cluster(heading, items) {
  return { heading, items };
}

function ch(fields) {
  return {
    kicker: "",
    paragraphs: [],
    clusters: [],
    steps: [],
    how: "",
    needs: "",
    note: "",
    pose: "accounts",
    group: "start",
    ...fields,
  };
}

export const site = {
  name: "RoboSEO.Ai",
  tagline: "SEO and social in one project",
};

export const groups = [
  { id: "start", label: "Start" },
  { id: "project", label: "Project" },
  { id: "search", label: "Search Console" },
  { id: "seo", label: "SEO" },
  { id: "blogs", label: "Blogs" },
  { id: "studio", label: "Blog Studio" },
  { id: "social", label: "Social" },
  { id: "toolkit", label: "Toolkit" },
  { id: "reports", label: "Reports" },
  { id: "admin", label: "Admin" },
  { id: "help", label: "Help" },
];

export const chapters = [
  ch({
    id: "intro",
    group: "start",
    pose: "accounts",
    title: "RoboSEO.Ai",
    lead: "SEO and social work for one project at a time. This page is the operator manual for every screen in the product.",
    how: "This is the public manual. The product itself is the signed-in workspace.",
    needs: "Nothing. Read it in order, or jump from the left rail.",
    paragraphs: [
      "A project is a website, a Meta page, or both. You pick one on All projects. Almost every tool then reads that project. Keyword Research, SERP Analysis, and Link Opportunities do not need a project. Admin and Knowledge Hub are also global.",
      "Electric blue is a win versus the prior period, a live state, or the primary action. Red is a loss, an error, or a destroy. Average position inverts that rule: a lower rank number is the win, so a rise of spots is worse and paints red.",
      "Blog Studio needs a real website. A Meta-only project can still run social: statistics, calendar, board, approvals, Create, autoscheduler, and Post Studio.",
    ],
    clusters: [
      cluster("How the workspace is laid out", [
        item("Project rail", "Dashboard, Search Console, SEO, Blogs, Social, Reports. These need a selected project. Search Console and SEO need a website, not only a Meta page."),
        item("Toolkit", "Keyword Research, SERP Analysis, Link Opportunities, Blog Studio, Post Studio. The first three are global. The studios write into the selected project."),
        item("Platform", "Admin (people, access, data sources) and Knowledge Hub. Guide lives in the header of each screen."),
      ]),
    ],
    note: "This manual matches the product as it ships. It is not a roadmap.",
  }),
  ch({
    id: "sign-in",
    group: "start",
    pose: "accounts",
    kicker: "Accounts",
    title: "Sign in, invite, verify, reset",
    lead: "You cannot sign in until an administrator invites you and you use the verification link.",
    how: "Open the product URL. Login, signup, forgot password, reset password, and verify email are their own pages.",
    needs: "An invite email that matches the address you use.",
    paragraphs: [
      "Invite creates the account and sends verification. Until that link is used, sign-in fails on purpose.",
      "Forgot password sends a reset link only if the address already has an account. The link expires. After reset, sign in with the new password.",
    ],
    clusters: [
      cluster("Sign in", [
        item("Email", "The address your administrator invited."),
        item("Password", "The one you set after verifying email."),
        item("Sign in", "Opens the dashboard for the projects you can access."),
      ]),
      cluster("Create account", [
        item("Name", "How you appear on approvals and the board."),
        item("Email", "Must match the invite. You verify it next."),
        item("Password", "At least six characters. Confirm it on the next field."),
        item("Create", "Sends the verification email."),
      ]),
      cluster("Reset and verify", [
        item("Forgot password", "Enter email, send link, check inbox."),
        item("New password", "Choose something you do not use elsewhere, then save."),
        item("Verify email", "Finishes the invite. If the link expired, ask an administrator to resend it."),
      ]),
    ],
    steps: [
      "Wait for the invite.",
      "Open the verification link.",
      "Set a password.",
      "Sign in.",
    ],
    note: "There is no public self-serve signup for people who were not invited.",
  }),
  ch({
    id: "all-projects",
    group: "project",
    pose: "projects",
    kicker: "Project",
    title: "All projects",
    lead: "Every website and social account you can open. Pick one card. The rest of the workspace follows that choice.",
    how: "Signed-in home for people with more than one project. The sidebar brand / All projects control returns you here.",
    needs: "A signed-in account with at least one assigned project.",
    paragraphs: [
      "Cards show a name, a domain or Meta page, and a health snapshot: clicks, impressions, and coverage versus the prior period. Blue is up. Red is down.",
      "Filter by name or domain when the list is long. Click a card to enter that project's Dashboard.",
      "Admin and Knowledge Hub stay available with no project selected. Toolkit research tools also stay available.",
    ],
    clusters: [
      cluster("On the page", [
        item("The list", "Every website and social account you can open."),
        item("Find a project", "Filter by name or domain."),
        item("Health snapshot", "Clicks, impressions, and coverage on the card."),
        item("Open", "Click a card to enter that project's dashboard and tools."),
      ]),
    ],
    note: "Nothing in the project workspace is global except Admin and Knowledge Hub. Switch projects here, not by editing URLs.",
  }),
  ch({
    id: "dashboard",
    group: "project",
    pose: "projects",
    kicker: "Project",
    title: "Dashboard",
    lead: "Headline Search Console numbers for the selected project in this period, plus top queries and pages.",
    how: "Sidebar: Dashboard. You must have a project selected.",
    needs: "Any project. Full SEO numbers need a website with Search Console connected.",
    paragraphs: [
      "Clicks are visits that landed from Search. Impressions are how often your pages showed. Average CTR is clicks divided by impressions, compared in percentage points when a prior block exists.",
      "Average position is lower-is-better. The badge says worse or better, not a naked plus. Example: last block 8.0, this block 10.4. That is 2.4 worse, in red. If it moved from 10.4 to 8.0, the badge reads 2.4 better, in blue. Clicks do not invert. More clicks is blue.",
      "Top queries and pages are a preview. Open Search Console, Statistics for the full tables, date range, and comparison.",
    ],
    clusters: [
      cluster("Cards", [
        item("Clicks", "Search visits that landed on the site in this period."),
        item("Impressions", "How often your pages showed in Google Search."),
        item("Average CTR", "Clicks divided by impressions."),
        item("Average position", "Lower is better. Worse stays red. Better stays blue. Spots, not a percent of the rank."),
        item("Top queries and pages", "What people search and which URLs they land on."),
      ]),
    ],
    note: "Dashboard is a snapshot. Statistics is where you change the date range.",
  }),
  ch({
    id: "gsc-statistics",
    group: "search",
    pose: "search",
    kicker: "Search Console",
    title: "Statistics",
    lead: "Clicks, impressions, CTR, and average position for a date range you choose. Comparison is optional.",
    how: "Sidebar: Search Console, then the Statistics tab.",
    needs: "A website project with Search Console.",
    paragraphs: [
      "Pick the period and an optional comparison. Totals, the chart, and the tables all follow that range.",
      "Toggle a metric card to show or hide that series on the chart.",
      "Worked example. Position 8.0 last block, 10.4 this block. Delta is +2.4 spots. That is 2.4 worse, red. Reverse the numbers and it is 2.4 better, blue. Clicks: more is blue, fewer is red.",
    ],
    clusters: [
      cluster("Controls", [
        item("Date range", "Period plus optional comparison."),
        item("Clicks", "Search visits for the selected dates."),
        item("Impressions", "How often you appeared in Search."),
        item("Average CTR", "Click-through rate. Comparison uses percentage points."),
        item("Average position", "Lower is better. Badges invert so an improved (lower) rank stays blue."),
        item("Pages, countries, queries", "The same totals broken down by URL, country, and search term."),
      ]),
    ],
    note: "This is Google's data for the property. It does not invent rankings.",
  }),
  ch({
    id: "url-inspection",
    group: "search",
    pose: "search",
    kicker: "Search Console",
    title: "URL Inspection",
    lead: "Live coverage for one URL on this Search Console property.",
    how: "Sidebar: Search Console, then URL Inspection.",
    needs: "A website project. The URL must belong to this property.",
    paragraphs: [
      "Paste a page. Inspect reads coverage, last crawl, and the declared canonical.",
      "Use it when you need to know whether Google can index the page, and why not if it cannot. It does not forecast rank.",
    ],
    clusters: [
      cluster("On the page", [
        item("URL", "Paste a page on this property."),
        item("Inspect", "Runs the live check."),
        item("Coverage", "Index status, last crawl, and declared canonical."),
      ]),
    ],
    steps: ["Paste the URL.", "Click Inspect.", "Read coverage before you chase rankings."],
    note: "Inspection will not invent rankings or crawl the whole site.",
  }),
  ch({
    id: "site-intelligence",
    group: "seo",
    pose: "site",
    kicker: "SEO",
    title: "Site Intelligence",
    lead: "One report for the selected website: audit, speed, authority, and backlinks. SE Ranking is the audit source.",
    how: "Sidebar: SEO, then Site Intelligence.",
    needs: "A website project.",
    paragraphs: [
      "Scores sit first. Strong scores use brand blue. Poor scores use red. Issues are ordered so the expensive ones sit on top.",
      "Export a PDF of the current view when you need to share it. This is this site's report, not a generic crawl of the internet.",
    ],
    clusters: [
      cluster("On the page", [
        item("The report", "Audit, speed, authority, and backlinks in one place."),
        item("Scores", "Health and authority figures."),
        item("Issues", "Crawl and on-page problems, expensive first."),
        item("Export", "Download a PDF of the current view."),
      ]),
    ],
    note: "Folded legacy screens (site audit, PageSpeed, domain authority, backlinks, explorer) all open here.",
  }),
  ch({
    id: "autopilot",
    group: "seo",
    pose: "site",
    kicker: "SEO",
    title: "SEO Autopilot",
    lead: "A run against this project's own site. Agents score, diagnose, and propose. Nothing publishes from here.",
    how: "Sidebar: SEO, then Autopilot.",
    needs: "A website project. Search Console, audit, and authority feed the briefing.",
    paragraphs: [
      "Start a pass. Auditor, Diagnoser, Fixer, and the rest work from live site context. Open an agent card to read or replace its skill.",
      "Scorecards, pitches, and drafts land in output. You approve a fix. Autopilot does not publish because a model felt confident.",
    ],
    clusters: [
      cluster("On the page", [
        item("Briefing", "Live site context: Search Console, audit, and authority."),
        item("Run", "Start a pass."),
        item("Agents", "Open a card to read or replace its skill."),
        item("Output", "Scorecards, pitches, and drafts. Nothing publishes without you."),
      ]),
    ],
    note: "This is not Blog Studio. Blog drafts are a different pipeline.",
  }),
  ch({
    id: "blog-board",
    group: "blogs",
    pose: "blogs",
    kicker: "Blogs",
    title: "Board",
    lead: "The queue of blog posts for this project, from draft through published.",
    how: "Sidebar: Blogs, then Board.",
    needs: "A selected project. Blog Studio later needs a website. The board can still hold posts for that project.",
    paragraphs: [
      "Drag a card to change status. Double-click to edit. Changes save immediately.",
      "Filter by assignee, site, or status when the board is busy.",
    ],
    clusters: [
      cluster("On the page", [
        item("Lanes", "Draft through published."),
        item("A post", "Double-click to edit. Saves immediately."),
        item("Filters", "Assignee, site, or status."),
      ]),
    ],
  }),
  ch({
    id: "blog-approvals",
    group: "blogs",
    pose: "blogs",
    kicker: "Blogs",
    title: "Approvals",
    lead: "Blogs waiting on a person. Approve schedules or publishes. Decline sends it back with a reason.",
    how: "Sidebar: Blogs, then Approvals.",
    needs: "A selected project, and permission to approve.",
    paragraphs: [
      "Open a draft, read it as it will appear, then approve or decline. Email quick-actions exist for the same decision.",
      "If the post came from WordPress, a decline can move it back to draft so it will not auto-publish.",
    ],
    clusters: [
      cluster("On the page", [
        item("Your queue", "Blogs waiting on you."),
        item("Approve or decline", "Approve schedules or publishes. Decline needs a reason."),
        item("Preview", "Read the article as it will appear."),
      ]),
    ],
    note: "Studio output waits here. It does not go live because a model finished.",
  }),
  ch({
    id: "create-blog",
    group: "blogs",
    pose: "blogs",
    kicker: "Blogs",
    title: "Create",
    lead: "A human starts a post when the machine should not. Title, slug, featured image, and the project it belongs to.",
    how: "Sidebar: Blogs, then Create.",
    needs: "A selected project.",
    paragraphs: [
      "Write or paste the article. Formatting and links stay intact. Send for approval moves it into the approval queue.",
      "If WordPress credentials are saved, you can pull existing posts instead of starting from a blank editor. Confirm credentials if the list is empty.",
    ],
    clusters: [
      cluster("On the page", [
        item("Editor", "Write or paste the article."),
        item("Details", "Title, slug, featured image, project."),
        item("Send for approval", "Moves the draft into the queue."),
        item("WordPress pull", "List pullable posts. Include trash if you need it, or pull by post ID."),
      ]),
    ],
  }),
  ch({
    id: "blog-autoscheduler",
    group: "blogs",
    pose: "blogs",
    kicker: "Blogs",
    title: "Autoscheduler",
    lead: "When approved blogs are allowed to go live. You set slots, cadence, timezone, and which queue feeds the calendar.",
    how: "Sidebar: Blogs, then Autoscheduler.",
    needs: "A selected project.",
    paragraphs: [
      "This publishes approved work into windows you set. It does not run keyword research overnight. Research is manual.",
      "Pause a date if you need to hold it. Upcoming shows the next pieces in line.",
    ],
    clusters: [
      cluster("On the page", [
        item("Slots", "Allowed publish windows."),
        item("Rules", "Cadence, timezone, and which queue feeds the calendar."),
        item("Upcoming", "The next pieces. Pause here to hold a date."),
      ]),
    ],
    note: "Autoscheduler publishes. It does not hunt for topics.",
  }),
  ch({
    id: "blog-studio-compose",
    group: "studio",
    pose: "studio",
    kicker: "Blog Studio",
    title: "Compose",
    lead: "Generate a draft for this website project. Leave the topic blank to run the Decider. Type a topic to skip it.",
    how: "Sidebar: Toolkit, Blog Studio. Zone: Compose.",
    needs: "A website project. Meta-only is not enough. Keys for the agents must be saved under Setup.",
    paragraphs: [
      "Sources: Topic, From Inbox, Excel queue, Research. Topic is the default. Inbox uses a saved item. Excel queue processes spreadsheet rows (max 50). Research builds or uses the keyword library first.",
      "Generate runs the prefix agents, then the draft. Watch the live rail. Open a step to read what it decided. Stop or re-run a step if the angle is wrong.",
    ],
    clusters: [
      cluster("Compose", [
        item("Topic", "Blank: Decider picks. Filled: Decider is skipped."),
        item("From Inbox", "Use a saved inbox item as the seed."),
        item("Excel queue", "One spreadsheet row per interval when Autopilot is on, or run now."),
        item("Research", "Build the project keyword library before deciding."),
        item("Generate", "Prefix agents, then the draft."),
        item("Live rail", "Each agent as it runs."),
      ]),
    ],
    note: "The Decider only picks from a closed ranked list. It does not invent a phrase.",
  }),
  ch({
    id: "blog-studio-research",
    group: "studio",
    pose: "keywords",
    kicker: "Blog Studio",
    title: "Research and keyword library",
    lead: "The library the Decider is allowed to see. Research does not invent terms outside what you give it and the live SERP.",
    how: "Blog Studio, Compose source Research, plus the research board. Optional: import your own phrases and turn on Use my keywords instead.",
    needs: "A website project. SerpAPI is required for world-trend ranking. Without it, ranking starts at overlap or the library.",
    paragraphs: [
      "Run research by hand. There is no overnight research cron.",
      "You can import an operator keyword bank and prefer that list. Filter junk after import. Turn the toggle off to return to the harvest library.",
    ],
    clusters: [
      cluster("Library", [
        item("Seed", "A keyword or domain."),
        item("Research", "Volume, difficulty, related terms."),
        item("Results", "Sort by volume or difficulty. Priority is a nudge, not a guarantee."),
        item("Operator bank", "Imported phrases. Optional replacement for harvest."),
      ]),
    ],
    note: "The list you take out of research is the list the Decider may see later.",
  }),
  ch({
    id: "blog-studio-prefix",
    group: "studio",
    pose: "studio",
    kicker: "Blog Studio",
    title: "Prefix agents and the draft",
    lead: "Decider, Binder, Checker, Headings, Architect, Writer, optional Humanizer, then Image.",
    how: "Triggered by Generate on Compose. Setup, Agents holds keys, models, and prompts.",
    needs: "Saved API keys for the agents you run. Humanizer is optional.",
    paragraphs: [
      "Decider order when the topic is blank: relevant world trends first (on-niche only), then overlap (a library phrase that matches a trend, or a Search Console query already in the library), then leftover library keywords. Closed list. No invented seeds. Binder still hangs the harvest keyword bag on whatever seed wins.",
      "Binder splits low-KD keywords into headings and higher KD into body. It does not invent keywords. Checker rephrases if the title collides in-app or, if enabled, with an exact Google organic title. Headings builds the outline. Architect writes the blueprint. Writer writes the draft.",
      "Humanizer is an optional rewrite plus a deterministic scrub of stock phrasing (including em dashes). If Humanizer returns empty HTML, the writer draft is kept and the scrub still runs. The run does not die on a blank model.",
      "Image generates a featured visual. Claude has no image API; use OpenAI or OpenRouter for that step.",
    ],
    clusters: [
      cluster("Rail order", [
        item("Decider", "World trends, then overlap, then library. Skip if you typed a topic."),
        item("Binder", "Keyword bag from harvest. Low KD in headings."),
        item("Checker", "Unique title."),
        item("Headings", "KD-aware outline."),
        item("Architect", "Article blueprint."),
        item("Writer", "Publication draft."),
        item("Humanizer", "Optional. Empty output keeps writer HTML."),
        item("Image", "Featured visual."),
      ]),
    ],
    note: "Output lands in the blog approval flow, not live.",
  }),
  ch({
    id: "blog-studio-setup",
    group: "studio",
    pose: "studio",
    kicker: "Blog Studio",
    title: "Setup",
    lead: "Voice, brand, links, assets, Autopilot schedule, agent keys, and optional external n8n.",
    how: "Blog Studio, zone Setup. Tabs across the top.",
    needs: "A website project.",
    paragraphs: [
      "Voice and Seeds: audience, standing seeds, brand notes that apply to every draft. Brand kit and Assets: visual guidelines and reference images. Links: destinations the writer may use. Autopilot: interval and source (seed prompt or Excel queue). Agents: provider, model, prompt per role. External n8n: a webhook if you run part of the chain outside the app.",
    ],
    clusters: [
      cluster("Tabs", [
        item("Voice and Seeds", "Audience, seeds, brand notes."),
        item("Brand kit", "Visual guidelines for generated images."),
        item("Links", "URLs the draft may include."),
        item("Assets", "Reference images."),
        item("Autopilot", "Interval and source. Does not run research."),
        item("Agents", "Keys, models, prompts. Save before Generate."),
        item("External n8n", "Optional webhook."),
      ]),
    ],
  }),
  ch({
    id: "smm-statistics",
    group: "social",
    pose: "social",
    kicker: "Social",
    title: "Statistics",
    lead: "Reach, engagement, and follower change for the selected project and period.",
    how: "Sidebar: Social, then Statistics.",
    needs: "Any project, including Meta-only.",
    paragraphs: [
      "Headline numbers use the same language as Search Console. Up is blue. Down is red. Facebook, Instagram, and the rest each have their own series.",
      "Build a slide deck from this window when you need to send the period out.",
    ],
    clusters: [
      cluster("On the page", [
        item("Period", "The window for the totals."),
        item("Headline numbers", "Reach, engagement, follower change."),
        item("Channels", "Each channel has its own series."),
        item("Report", "Build a slide deck from this period."),
      ]),
    ],
  }),
  ch({
    id: "calendar",
    group: "social",
    pose: "social",
    kicker: "Social",
    title: "Calendar",
    lead: "Posts and blogs plotted on the days they go out.",
    how: "Sidebar: Social, then Calendar.",
    needs: "A selected project.",
    paragraphs: [
      "Click a date to add or inspect items scheduled there. Open an item to edit copy or move the date.",
    ],
    clusters: [
      cluster("On the page", [
        item("The month", "Posts and blogs on the days they go out."),
        item("A day", "Click to add or inspect."),
        item("An item", "Status and channel. Open to edit or move."),
      ]),
    ],
  }),
  ch({
    id: "post-board",
    group: "social",
    pose: "social",
    kicker: "Social",
    title: "Board",
    lead: "Social posts from idea to published.",
    how: "Sidebar: Social, then Board.",
    needs: "A selected project.",
    paragraphs: [
      "Drag a card to change status. Double-click to edit caption, media, and schedule. Filter by channel, assignee, or status.",
    ],
    clusters: [
      cluster("On the page", [
        item("Lanes", "Idea through published."),
        item("A post", "Caption, media, schedule."),
        item("Filters", "Channel, assignee, or status."),
      ]),
    ],
  }),
  ch({
    id: "post-approvals",
    group: "social",
    pose: "social",
    kicker: "Social",
    title: "Approvals",
    lead: "Social posts waiting on you. Same refuse-or-ship motion as blogs.",
    how: "Sidebar: Social, then Approvals.",
    needs: "A selected project, and permission to approve.",
    paragraphs: [
      "Preview caption and creative. Approve sends it toward publish. Decline returns it with a note.",
    ],
    clusters: [
      cluster("On the page", [
        item("Your queue", "Social posts waiting on you."),
        item("Approve or decline", "Approve toward publish. Decline with a note."),
        item("Preview", "Caption and creative before you sign off."),
      ]),
    ],
  }),
  ch({
    id: "create-post",
    group: "social",
    pose: "social",
    kicker: "Social",
    title: "Create",
    lead: "Write the post yourself. Attach images or video. Choose channel and time.",
    how: "Sidebar: Social, then Create.",
    needs: "A selected project.",
    paragraphs: [
      "Send for approval drops it in the queue. It does not publish from this screen.",
    ],
    clusters: [
      cluster("On the page", [
        item("Caption", "Write the post. Attach media on the side."),
        item("Channel and time", "Where it publishes and when."),
        item("Send for approval", "Drops it in the queue."),
      ]),
    ],
  }),
  ch({
    id: "post-autoscheduler",
    group: "social",
    pose: "social",
    kicker: "Social",
    title: "Autoscheduler",
    lead: "Allowed publish windows for social posts, per channel and timezone.",
    how: "Sidebar: Social, then Autoscheduler.",
    needs: "A selected project.",
    paragraphs: [
      "Hold a slot if the date needs to move. This publishes approved posts. It does not write them.",
    ],
    clusters: [
      cluster("On the page", [
        item("Slots", "Allowed windows."),
        item("Rules", "Cadence per channel and timezone."),
        item("Upcoming", "What is next. Hold a slot to move a date."),
      ]),
    ],
  }),
  ch({
    id: "post-studio",
    group: "social",
    pose: "studio",
    kicker: "Social",
    title: "Post Studio",
    lead: "A brief, a channel, a strategist, a copywriter. Output lands in approval, not live.",
    how: "Sidebar: Toolkit, Post Studio.",
    needs: "Any project, including Meta-only. Agent keys saved.",
    paragraphs: [
      "Generate runs Strategist then Copywriter. Follow the live rail. Stop or re-run a step if the angle is wrong. The library keeps earlier runs for this project.",
    ],
    clusters: [
      cluster("On the page", [
        item("Brief", "What the post is about and which channel it is for."),
        item("Generate", "Strategist then copywriter."),
        item("Live rail", "Follow each agent."),
        item("Library", "Earlier runs for this project."),
      ]),
    ],
    note: "Nothing posts itself from Post Studio.",
  }),
  ch({
    id: "keyword-research",
    group: "toolkit",
    pose: "keywords",
    kicker: "Toolkit",
    title: "Keyword Research",
    lead: "Volume, difficulty, and related terms from a seed or a domain. No website project required.",
    how: "Sidebar: Toolkit, Keyword Research. Usable with nothing selected, or with a Meta-only project.",
    needs: "A seed keyword or a domain. Not gated on the selected project.",
    paragraphs: [
      "Research does not invent terms outside what you give it and the live SERP. Sort by volume or difficulty. Priority is a nudge, not a guarantee. Export the table when you want it in a sheet.",
      "This list is what Blog Studio's Decider is allowed to see later if you run research for that website.",
    ],
    clusters: [
      cluster("On the page", [
        item("Seed", "Type a keyword or paste a domain."),
        item("Research", "Pulls volume, difficulty, and related terms."),
        item("Results", "Sort by volume or difficulty."),
        item("Export", "Download the table."),
      ]),
    ],
  }),
  ch({
    id: "serp-analysis",
    group: "toolkit",
    pose: "search",
    kicker: "Toolkit",
    title: "SERP Analysis",
    lead: "A live snapshot of the top results for a query, your rank if you are in them, and competitor pages.",
    how: "Sidebar: Toolkit, SERP Analysis. Global: no website required.",
    needs: "A query.",
    paragraphs: [
      "Your position is where you sit. Above you is a warning that someone ranks higher, not a growth badge.",
      "How to move up lists concrete gaps on the pages beating you: headings, speed, missing terms.",
    ],
    clusters: [
      cluster("On the page", [
        item("Query", "The search you want a snapshot of."),
        item("Analyze", "Live top results, your rank, competitor pages."),
        item("Your position", "Where you sit."),
        item("How to move up", "Gaps on the pages beating you."),
      ]),
    ],
  }),
  ch({
    id: "link-opportunities",
    group: "toolkit",
    pose: "links",
    kicker: "Toolkit",
    title: "Link Opportunities",
    lead: "Prospects that already rank on related terms or link to similar pages.",
    how: "Sidebar: Toolkit, Link Opportunities. Global.",
    needs: "A target page or domain.",
    paragraphs: [
      "Each prospect has a domain, overlap, and a reason it is on the list. Export when you are ready to outreach.",
    ],
    clusters: [
      cluster("On the page", [
        item("Target", "The page or domain you want links toward."),
        item("Find", "Prospects from related ranks or similar links."),
        item("Prospects", "Domain, overlap, reason. Export the list."),
      ]),
    ],
  }),
  ch({
    id: "report-studio",
    group: "reports",
    pose: "reports",
    kicker: "Reports",
    title: "Report Studio",
    lead: "A designed pack for the selected project. Website, social, or combined. Live data for the month you pick.",
    how: "Sidebar: Reports.",
    needs: "A selected project.",
    paragraphs: [
      "Build generates the PDF. Send it from here or download it. Sent reports stay in history so you do not double-send.",
      "The robot mark sits in the header of the PDF and the slide deck.",
    ],
    clusters: [
      cluster("On the page", [
        item("Report type", "Website, social, or combined landscape decks."),
        item("Month", "The reporting period."),
        item("Build", "Generates the PDF. Send or download."),
        item("Sent reports", "What already went out."),
      ]),
    ],
  }),
  ch({
    id: "admin",
    group: "admin",
    pose: "admin",
    kicker: "Admin",
    title: "People, access, data sources",
    lead: "Who can sign in, which projects and tools they may open, and the keys Trends and duplicate checks use.",
    how: "Sidebar: Admin. Global. No project required.",
    needs: "Administrator access.",
    paragraphs: [
      "People: invite, deactivate, change a role. Invite creates an account and sends verification. Access is a list of projects and tools, not a rumour.",
      "Data sources: paste a SerpAPI key to turn world-trend ranking on for the Decider. Without it, drafts still use the keyword library and world-trend seeds stay off. Check Google for duplicate titles is one quoted search per draft; off means in-app titles only.",
      "When Trends are off, Decider fallback ranking is Research library (featured and universe keywords, prefers gap/strike, low KD, real volume) or Search Console overlap with the library.",
    ],
    clusters: [
      cluster("People", [
        item("People", "Everyone who can sign in."),
        item("Access", "Which projects and tools a person can open."),
        item("Invite", "Creates an account and sends verification."),
      ]),
      cluster("Data sources", [
        item("SerpAPI", "World trends for the Decider. Off: library only."),
        item("Duplicate titles", "Optional Google check per draft."),
        item("Library ranking", "Used when Trends are off, or when no on-niche world trend exists."),
      ]),
    ],
  }),
  ch({
    id: "guide",
    group: "help",
    pose: "help",
    kicker: "Help",
    title: "Guide",
    lead: "A spotlight on this screen: the metric, the date range, the Generate button. Not a knowledge-base article.",
    how: "Header, right side, on each workspace screen. Shorter tours exist on login, signup, and reset.",
    needs: "You are on the screen you want explained.",
    paragraphs: [
      "Next moves the hole. The label stays on the page. Esc closes it. If a target is missing, the dim stays and the card sits in the centre. There is never a hanging label with no hole.",
      "One Guide per section. Use it for how that screen works. Longer explainers live in Knowledge Hub.",
    ],
    clusters: [
      cluster("On the page", [
        item("On the workspace", "Header, right side."),
        item("On sign-in", "A shorter tour for login, signup, and reset."),
        item("The hole", "A cutout over the control, plus a card clamped inside the viewport."),
      ]),
    ],
  }),
  ch({
    id: "knowledge-hub",
    group: "help",
    pose: "help",
    kicker: "Help",
    title: "Knowledge Hub",
    lead: "Short explainers (Core Web Vitals, third-party scripts, and the rest). They do not change project data.",
    how: "Sidebar: Knowledge Hub.",
    needs: "Signed in. No project required.",
    paragraphs: [
      "Search by topic. Open an article and read it here. For how a specific control works, use Guide on that screen instead.",
    ],
    clusters: [
      cluster("On the page", [
        item("Search", "Find an article by topic."),
        item("Articles", "Short explainers, not the in-page Guide."),
        item("The article", "Read it here. It does not change your project data."),
      ]),
    ],
  }),
  ch({
    id: "rules",
    group: "help",
    pose: "help",
    kicker: "Help",
    title: "Operating rules",
    lead: "Limits the product already follows. Not a roadmap hedge.",
    how: "This chapter. The same rules are enforced in Blog Studio, research, and autoscheduler.",
    needs: "None.",
    paragraphs: [
      "The Decider prefers a relevant world trend, then overlap (library times trend, or Search Console intersect library), then leftover library keywords. It never invents a term.",
      "Keyword research runs when you ask. Autoscheduler publishes approved work. It does not go hunting overnight.",
      "Blog Studio needs a website project. A Meta-only account can still run social.",
      "Studio output waits for a person. Average position inverts: a rise in spots is worse. Clicks do not invert.",
    ],
    clusters: [
      cluster("The rules", [
        item("Closed list", "Decider never invents a seed phrase."),
        item("No research cron", "You run research. Autoscheduler only publishes."),
        item("Website for blogs", "Blog Studio needs a website."),
        item("Approvals stay human", "Nothing posts because a model finished."),
        item("Position badge", "8.0 to 10.4 is 2.4 worse. Reverse is 2.4 better."),
      ]),
    ],
    footer: "RoboSEO.Ai. AI powered SEO and SMM automation.",
  }),
];
